server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy6Tfr1kVIGpP